"""PR-122 Phase 1 — ``effects`` attribute + GitHub PR effector.

Locks in the smallest-viable-slice contract:

- ``NodeDefinition.effects`` round-trips through ``to_dict`` / ``from_dict``.
- ``effects`` survives the ``build_branch`` → ``get_branch`` storage path.
- The effector parses ``external_write_packet`` shapes out of run state.
- Dry-run mode returns intent without invoking ``gh``.
- Real-run mode shells to ``gh pr create`` (subprocess mocked) and
  parses ``pr_url`` / ``pr_number`` out of stdout.
- Errors are surfaced as structured evidence, never raised.
- Nodes without ``effects`` are not touched.
"""

from __future__ import annotations

import importlib
import json
import subprocess
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from workflow.branches import BranchDefinition, NodeDefinition
from workflow.effectors import (
    EXTERNAL_WRITE_SINK_GITHUB_PR,
    run_effects_for_branch,
    run_github_pr_effector,
)
from workflow.effectors.github_pr import PHASE_1_IDEMPOTENCY_ACK

# ─── 1. NodeDefinition.effects round-trip ─────────────────────────────────


def test_node_definition_effects_default_empty_list():
    node = NodeDefinition(node_id="n1", display_name="N1")
    assert node.effects == []


def test_node_definition_effects_to_dict_from_dict_roundtrip():
    node = NodeDefinition(
        node_id="emit_pr",
        display_name="Emit PR",
        prompt_template="Draft a PR for {topic}",
        output_keys=["pr_packet"],
        effects=["github_pull_request"],
    )
    blob = node.to_dict()
    assert blob["effects"] == ["github_pull_request"]
    revived = NodeDefinition.from_dict(blob)
    assert revived.effects == ["github_pull_request"]


def test_node_definition_effects_must_be_list_of_strings():
    from workflow.branches import NodeDefinitionValidationError

    with pytest.raises(NodeDefinitionValidationError):
        NodeDefinition(node_id="n1", display_name="N1", effects="github_pr")
    with pytest.raises(NodeDefinitionValidationError):
        NodeDefinition(
            node_id="n1", display_name="N1", effects=[123],  # type: ignore[list-item]
        )


# ─── 2. build_branch → get_branch storage path ────────────────────────────


@pytest.fixture
def comp_env(tmp_path, monkeypatch):
    base = tmp_path / "output"
    base.mkdir()
    monkeypatch.setenv("WORKFLOW_DATA_DIR", str(base))
    monkeypatch.setenv("UNIVERSE_SERVER_USER", "tester")
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", raising=False)
    from workflow import universe_server as us

    importlib.reload(us)
    yield us, base
    importlib.reload(us)


def _call(us, action, **kwargs):
    return json.loads(us.extensions(action=action, **kwargs))


_SPEC_WITH_EFFECTS = {
    "name": "PR emitter",
    "description": "Single-node branch that emits an external_write_packet",
    "entry_point": "draft",
    "node_defs": [
        {
            "node_id": "draft",
            "display_name": "Draft PR",
            "prompt_template": "Make a PR for {topic}",
            "input_keys": ["topic"],
            "output_keys": ["pr_packet"],
            "effects": ["github_pull_request"],
        },
    ],
    "edges": [
        {"from": "START", "to": "draft"},
        {"from": "draft", "to": "END"},
    ],
    "state_schema": [
        {"name": "topic", "type": "str"},
        {"name": "pr_packet", "type": "str"},
    ],
}


def test_build_branch_persists_effects_attribute(comp_env):
    us, _ = comp_env
    built = _call(us, "build_branch", spec_json=json.dumps(_SPEC_WITH_EFFECTS))
    assert built["status"] == "built", built
    bid = built["branch_def_id"]
    got = _call(us, "get_branch", branch_def_id=bid)
    node_defs = got.get("node_defs") or []
    assert node_defs, f"expected node_defs in get_branch, got {got!r}"
    draft = next(n for n in node_defs if n["node_id"] == "draft")
    assert draft["effects"] == ["github_pull_request"]


def test_build_branch_rejects_non_list_effects(comp_env):
    us, _ = comp_env
    spec = dict(_SPEC_WITH_EFFECTS)
    spec["node_defs"] = [
        {**spec["node_defs"][0], "effects": "github_pull_request"},
    ]
    result = _call(us, "build_branch", spec_json=json.dumps(spec))
    # Either status=invalid OR an explicit error string surfaces.
    text = json.dumps(result)
    assert "effects" in text, result


# ─── 3. Effector — parses external_write_packet shape ─────────────────────


_PACKET = {
    "sink": EXTERNAL_WRITE_SINK_GITHUB_PR,
    "payload": {
        "title": "Loop 2 cycle 001: fix BUG-049",
        "body": "Generated by Loop 2 workflow run.",
        "base_branch": "main",
        "head_branch": "auto/loop-2/cycle-001",
        "labels": ["writer:loop-2"],
        "draft": True,
    },
    "idempotency_hint": "loop-2-cycle-001-fix-bug-049",
    "expected_evidence_keys": ["pr_number", "pr_url"],
}

# PR-122 Phase 1 round-2: real-write paths require explicit ack until
# Phase 2 ships real idempotency. Existing real-run tests pass the ack
# so they exercise the gh-invocation code path.
_ACKED_PACKET = {**_PACKET, "idempotency_ack": PHASE_1_IDEMPOTENCY_ACK}


def test_effector_dry_run_returns_intent_without_invoking_gh():
    out_state = {"pr_packet": _PACKET}
    with patch("workflow.effectors.github_pr.subprocess.run") as mock_run:
        result = run_github_pr_effector(
            node_id="draft",
            output_keys=["pr_packet"],
            run_state=out_state,
            dry_run=True,
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["intent"]["sink"] == EXTERNAL_WRITE_SINK_GITHUB_PR
    assert result["matched_output_key"] == "pr_packet"


def test_effector_dry_run_env_flag_also_engages(monkeypatch):
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", "1")
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="draft",
                display_name="Draft",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    run_state = {"pr_packet": _PACKET}
    with patch("workflow.effectors.github_pr.subprocess.run") as mock_run:
        ev_map = run_effects_for_branch(branch=branch, run_state=run_state)
    mock_run.assert_not_called()
    assert ev_map["draft"][EXTERNAL_WRITE_SINK_GITHUB_PR]["dry_run"] is True


def test_effector_parses_json_string_packet():
    """Authors may emit the packet as a JSON string from prompt-template
    nodes (since prompt templates emit strings, not dicts). The effector
    should still parse it."""
    out_state = {"pr_packet": json.dumps(_PACKET)}
    result = run_github_pr_effector(
        node_id="draft",
        output_keys=["pr_packet"],
        run_state=out_state,
        dry_run=True,
    )
    assert result["dry_run"] is True
    assert result["intent"]["payload"]["title"].startswith("Loop 2")


def test_effector_skips_non_packet_output_values():
    """Other output keys with plain string values must be silently skipped
    — they're normal outputs, not packets. The matching packet wins."""
    out_state = {
        "summary": "Some plain text output",
        "pr_packet": _PACKET,
    }
    result = run_github_pr_effector(
        node_id="draft",
        output_keys=["summary", "pr_packet"],
        run_state=out_state,
        dry_run=True,
    )
    assert result["dry_run"] is True
    assert result["matched_output_key"] == "pr_packet"


def test_effector_real_run_invokes_gh_pr_create_and_parses_evidence():
    out_state = {"pr_packet": _ACKED_PACKET}
    fake_completed = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/owner/repo/pull/4242\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value="/usr/bin/gh",
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake_completed,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="draft",
            output_keys=["pr_packet"],
            run_state=out_state,
            dry_run=False,
        )
    assert mock_run.called
    cmd = mock_run.call_args.args[0]
    assert cmd[:3] == ["gh", "pr", "create"]
    assert "--title" in cmd
    assert "--draft" in cmd
    assert "--head" in cmd
    assert "auto/loop-2/cycle-001" in cmd
    assert result["pr_url"] == "https://github.com/owner/repo/pull/4242"
    assert result["pr_number"] == 4242
    assert "error" not in result


def test_effector_returns_error_when_gh_missing():
    out_state = {"pr_packet": _ACKED_PACKET}
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value=None,
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="draft",
            output_keys=["pr_packet"],
            run_state=out_state,
            dry_run=False,
        )
    mock_run.assert_not_called()
    assert result["error_kind"] == "gh_not_installed"


def test_effector_returns_error_when_gh_exits_nonzero():
    out_state = {"pr_packet": _ACKED_PACKET}
    fake_completed = SimpleNamespace(
        returncode=1,
        stdout="",
        stderr="fatal: branch already exists\n",
    )
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value="/usr/bin/gh",
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake_completed,
    ):
        result = run_github_pr_effector(
            node_id="draft",
            output_keys=["pr_packet"],
            run_state=out_state,
            dry_run=False,
        )
    assert result["error_kind"] == "gh_nonzero_exit"
    assert "branch already exists" in result["error"]


def test_effector_returns_error_when_no_matching_packet():
    out_state = {"pr_packet": "this is plain text, not a packet"}
    result = run_github_pr_effector(
        node_id="draft",
        output_keys=["pr_packet"],
        run_state=out_state,
        dry_run=True,
    )
    assert result["error_kind"] == "no_matching_packet"


def test_effector_returns_error_when_payload_missing_title():
    bad_packet = {
        "sink": EXTERNAL_WRITE_SINK_GITHUB_PR,
        "payload": {"body": "no title"},
        "idempotency_ack": PHASE_1_IDEMPOTENCY_ACK,
    }
    out_state = {"pr_packet": bad_packet}
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value="/usr/bin/gh",
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="draft",
            output_keys=["pr_packet"],
            run_state=out_state,
            dry_run=False,
        )
    mock_run.assert_not_called()
    assert result["error_kind"] == "invalid_payload"


def test_effector_returns_error_when_subprocess_raises():
    out_state = {"pr_packet": _ACKED_PACKET}
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value="/usr/bin/gh",
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
        side_effect=subprocess.TimeoutExpired(cmd="gh", timeout=60.0),
    ):
        result = run_github_pr_effector(
            node_id="draft",
            output_keys=["pr_packet"],
            run_state=out_state,
            dry_run=False,
        )
    assert result["error_kind"] == "gh_invocation_failed"


# ─── 4. Branch-level dispatch ─────────────────────────────────────────────


def test_run_effects_for_branch_skips_nodes_without_effects():
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="plain",
                display_name="Plain",
                output_keys=["summary"],
            ),
            NodeDefinition(
                node_id="emit",
                display_name="Emit",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    run_state = {
        "summary": "plain text",
        "pr_packet": _PACKET,
    }
    ev_map = run_effects_for_branch(
        branch=branch, run_state=run_state, dry_run=True,
    )
    assert set(ev_map.keys()) == {"emit"}


def test_run_effects_for_branch_no_op_when_no_effects_declared():
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="plain",
                display_name="Plain",
                output_keys=["summary"],
            ),
        ],
    )
    ev_map = run_effects_for_branch(
        branch=branch, run_state={"summary": "x"}, dry_run=True,
    )
    assert ev_map == {}


def test_run_effects_for_branch_records_unknown_sink():
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="emit",
                display_name="Emit",
                output_keys=["packet"],
                effects=["twitter_post"],  # not yet supported
            ),
        ],
    )
    ev_map = run_effects_for_branch(
        branch=branch, run_state={"packet": "x"}, dry_run=True,
    )
    assert ev_map["emit"]["twitter_post"]["error_kind"] == "unknown_sink"


# ─── 5. Error collection helper ───────────────────────────────────────────


def test_collect_external_write_errors_flattens_error_rows():
    from workflow.runs import _collect_external_write_errors

    evidence = {
        "draft": {
            EXTERNAL_WRITE_SINK_GITHUB_PR: {
                "error": "gh CLI not installed",
                "error_kind": "gh_not_installed",
            },
        },
        "other": {
            "twitter_post": {
                "error": "unknown effect sink 'twitter_post'",
                "error_kind": "unknown_sink",
            },
        },
        "ok": {
            EXTERNAL_WRITE_SINK_GITHUB_PR: {
                "pr_url": "https://example/pr/1",
                "pr_number": 1,
            },
        },
    }
    errors = _collect_external_write_errors(evidence)
    kinds = {(row["node_id"], row["sink"], row["error_kind"]) for row in errors}
    assert kinds == {
        ("draft", EXTERNAL_WRITE_SINK_GITHUB_PR, "gh_not_installed"),
        ("other", "twitter_post", "unknown_sink"),
    }


# ─── 6. BranchDefinition node_defs roundtrip through full to_dict path ────


# ─── 7. PR-122 Phase 1 round-2 — Codex review hardening ───────────────────
# Default dry-run, explicit-enable-required, idempotency-ack-required,
# system-authoritative receipts. See PR #955 review thread for the
# verbatim findings.


def test_effector_defaults_to_dry_run_without_explicit_enable(monkeypatch):
    """Out of the box (no env vars set), the effector returns dry-run
    intent — no subprocess.run call.

    Codex finding #1: external writes must default to dry-run with an
    explicit consent gate."""
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_ENABLED", raising=False)
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", raising=False)
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="draft",
                display_name="Draft",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    with patch("workflow.effectors.github_pr.subprocess.run") as mock_run:
        ev_map = run_effects_for_branch(
            branch=branch, run_state={"pr_packet": _ACKED_PACKET},
        )
    mock_run.assert_not_called()
    ev = ev_map["draft"][EXTERNAL_WRITE_SINK_GITHUB_PR]
    assert ev["dry_run"] is True
    assert ev["enabled_explicit"] is False
    assert "WORKFLOW_EXTERNAL_WRITE_ENABLED" in ev["reason"]


def test_effector_real_write_requires_explicit_enable_env(monkeypatch):
    """When WORKFLOW_EXTERNAL_WRITE_ENABLED is truthy AND the packet
    carries the idempotency ack, the effector invokes gh pr create."""
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_ENABLED", "1")
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", raising=False)
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="draft",
                display_name="Draft",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    fake_completed = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/owner/repo/pull/77\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value="/usr/bin/gh",
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake_completed,
    ) as mock_run:
        ev_map = run_effects_for_branch(
            branch=branch, run_state={"pr_packet": _ACKED_PACKET},
        )
    assert mock_run.called
    ev = ev_map["draft"][EXTERNAL_WRITE_SINK_GITHUB_PR]
    assert ev["pr_number"] == 77
    assert ev["enabled_explicit"] is True


def test_effector_real_write_requires_idempotency_ack(monkeypatch):
    """Even with WORKFLOW_EXTERNAL_WRITE_ENABLED set, a packet without
    the explicit idempotency ack must NOT shell to gh.

    Codex finding #3: duplicate PR risk in Phase 1 — block real writes
    behind explicit acknowledgement until Phase 2 ships dedupe."""
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_ENABLED", "1")
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", raising=False)
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="draft",
                display_name="Draft",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    # _PACKET has NO idempotency_ack.
    with patch(
        "workflow.effectors.github_pr.shutil.which",
        return_value="/usr/bin/gh",
    ), patch(
        "workflow.effectors.github_pr.subprocess.run",
    ) as mock_run:
        ev_map = run_effects_for_branch(
            branch=branch, run_state={"pr_packet": _PACKET},
        )
    mock_run.assert_not_called()
    ev = ev_map["draft"][EXTERNAL_WRITE_SINK_GITHUB_PR]
    assert ev["error_kind"] == "idempotency_phase_1_guard"
    assert ev["dry_run"] is True
    assert PHASE_1_IDEMPOTENCY_ACK in ev["message"]


def test_effector_legacy_dry_run_env_still_forces_dry_run(monkeypatch):
    """Back-compat: when the legacy WORKFLOW_EXTERNAL_WRITE_DRY_RUN is
    truthy, it forces dry-run even if WORKFLOW_EXTERNAL_WRITE_ENABLED is
    also set. Preserves intent for operators who set the old gate."""
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_ENABLED", "1")
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", "1")
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="draft",
                display_name="Draft",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    with patch("workflow.effectors.github_pr.subprocess.run") as mock_run:
        ev_map = run_effects_for_branch(
            branch=branch, run_state={"pr_packet": _ACKED_PACKET},
        )
    mock_run.assert_not_called()
    ev = ev_map["draft"][EXTERNAL_WRITE_SINK_GITHUB_PR]
    assert ev["dry_run"] is True


def test_runs_moves_branch_authored_external_write_results_to_quarantine():
    """If a branch's output already contains ``external_write_results``,
    that value must be quarantined to ``_branch_authored_*`` BEFORE the
    effector runs.

    Codex finding #2: external-write receipts must be
    system-authoritative; a user-authored receipt cannot win."""
    from workflow.runs import _quarantine_branch_authored_external_write_keys

    output = {
        "summary": "real output",
        "external_write_results": [{"fake": "user-authored receipt"}],
    }
    _quarantine_branch_authored_external_write_keys(output)
    assert "external_write_results" not in output
    assert output["_branch_authored_external_write_results"] == [
        {"fake": "user-authored receipt"},
    ]


def test_runs_moves_branch_authored_external_write_errors_to_quarantine():
    """Same quarantine treatment for the errors key."""
    from workflow.runs import _quarantine_branch_authored_external_write_keys

    output = {
        "external_write_errors": [{"forged": "error row"}],
    }
    _quarantine_branch_authored_external_write_keys(output)
    assert "external_write_errors" not in output
    assert output["_branch_authored_external_write_errors"] == [
        {"forged": "error row"},
    ]


def test_runs_quarantine_no_op_when_keys_absent():
    """When the branch did not pre-populate either key, quarantine is
    a no-op — no spurious keys appear."""
    from workflow.runs import _quarantine_branch_authored_external_write_keys

    output = {"summary": "x"}
    _quarantine_branch_authored_external_write_keys(output)
    assert output == {"summary": "x"}


def test_runs_external_write_results_overwrites_quarantined_value():
    """End-to-end: when the branch tries to forge a receipt, the
    system overwrites at the canonical key with the real evidence
    and preserves the forgery under a quarantined key."""
    from workflow.runs import (
        _quarantine_branch_authored_external_write_keys,
    )

    output = {
        "summary": "real",
        "external_write_results": {"fake": "forgery"},
        "external_write_errors": [{"fake": "row"}],
    }
    # Simulate the start_run / resume_run sequence:
    _quarantine_branch_authored_external_write_keys(output)
    fake_system_evidence = {"draft": {"github_pull_request": {"pr_number": 99}}}
    output["external_write_results"] = fake_system_evidence  # unconditional
    assert output["external_write_results"] == fake_system_evidence
    assert output["_branch_authored_external_write_results"] == {
        "fake": "forgery",
    }
    assert output["_branch_authored_external_write_errors"] == [{"fake": "row"}]


def test_branch_definition_node_def_effects_survive_branch_to_dict():
    branch = BranchDefinition(
        name="emit-pr",
        domain_id="loop-2",
        node_defs=[
            NodeDefinition(
                node_id="draft",
                display_name="Draft",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    blob = branch.to_dict()
    revived = BranchDefinition.from_dict(blob)
    assert revived.node_defs[0].effects == [EXTERNAL_WRITE_SINK_GITHUB_PR]
