"""PR-122 Phase 2 — three-gate authority for the GitHub PR effector.

Covers:
  - Each gate failure case independently:
      * no destination on packet -> Phase 1 backward-compat dry-run
      * destination + missing capability env -> Phase 2 dry-run
      * destination + capability + missing consent grant -> Phase 2 dry-run
      * idempotency receipt already present -> dedup hit, no subprocess
  - Happy path with all three gates open -> real subprocess invocation +
    receipt recorded
  - Concurrent retries with the same idempotency_hint -> second call
    returns dedup hit without re-invoking gh
  - JSON-map capability lookup (round-2 P1.2 fix) — distinct
    destinations with punctuation that collided under the round-1
    encoding now resolve to distinct tokens
  - Subprocess is fully mocked; no test touches real GitHub
  - Failure paths (gh exit nonzero / missing / timeout / no-URL-in-stdout)
    do NOT leave terminal-succeeded receipts; the reserved row is
    released to status=failed so a retry can re-reserve

Round-2 atomicity tests live in tests/test_external_write_phase_2_atomicity.py.
"""

from __future__ import annotations

import json
import os
import subprocess
import urllib.error
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from workflow.branches import NodeDefinition
from workflow.effectors import EXTERNAL_WRITE_SINK_GITHUB_PR
from workflow.effectors.github_pr import (
    _CAPABILITIES_ENV,
    _read_capability,
    run_effects_for_branch,
    run_github_pr_effector,
)
from workflow.storage.effector_consents import grant_consent
from workflow.storage.external_write_receipts import (
    STATUS_FAILED,
    STATUS_PENDING,
    STATUS_SUCCEEDED,
    lookup_receipt,
    record_receipt,
)

_DESTINATION = "Jonnyton/Workflow"
_HEAD_BRANCH = "auto/loop-2/cycle-001"


def _make_packet(
    *,
    destination: str | None = _DESTINATION,
    idempotency_hint: str | None = "loop-2-cycle-001",
    head_branch: str = _HEAD_BRANCH,
    title: str = "Loop 2 cycle 001: fix BUG-049",
) -> dict:
    packet = {
        "sink": EXTERNAL_WRITE_SINK_GITHUB_PR,
        "payload": {
            "title": title,
            "body": "Generated by Loop 2 workflow run.",
            "base_branch": "main",
            "head_branch": head_branch,
            "labels": ["writer:loop-2"],
            "draft": True,
        },
        "expected_evidence_keys": ["pr_number", "pr_url"],
    }
    if destination is not None:
        packet["destination"] = destination
    if idempotency_hint is not None:
        packet["idempotency_hint"] = idempotency_hint
    return packet


@pytest.fixture
def universe_dir(tmp_path):
    """Per-test universe directory the effector can use for the storage gates."""
    universe = tmp_path / "u-test"
    universe.mkdir()
    return universe


@pytest.fixture(autouse=True)
def _clean_capability_env(monkeypatch):
    """Strip host-shell capability env state for isolated tests.

    Both the round-2 JSON-map env and any stale round-1 per-destination
    suffix env vars are cleared so test outcomes don't depend on the
    developer's shell state.
    """
    monkeypatch.delenv(_CAPABILITIES_ENV, raising=False)
    for name in list(os.environ.keys()):
        if name.startswith("WORKFLOW_GITHUB_PR_CAPABILITY_REPO_"):
            monkeypatch.delenv(name, raising=False)
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_ENABLED", raising=False)
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", raising=False)


def _set_capability(monkeypatch, destination: str, token: str) -> None:
    """Set the JSON-map capability env to ``{destination: token}``."""
    existing_raw = os.environ.get(_CAPABILITIES_ENV, "").strip()
    cap_map: dict[str, str] = {}
    if existing_raw:
        try:
            parsed = json.loads(existing_raw)
            if isinstance(parsed, dict):
                cap_map = {
                    k: v for k, v in parsed.items()
                    if isinstance(k, str) and isinstance(v, str)
                }
        except ValueError:
            cap_map = {}
    cap_map[destination] = token
    monkeypatch.setenv(_CAPABILITIES_ENV, json.dumps(cap_map))


# ---------------------------------------------------------------------------
# Capability lookup — JSON-map (round-2 P1.2 fix)
# ---------------------------------------------------------------------------


def test_read_capability_via_json_map(monkeypatch):
    monkeypatch.setenv(
        _CAPABILITIES_ENV,
        json.dumps({"Jonnyton/Workflow": "tok-A"}),
    )
    assert _read_capability("Jonnyton/Workflow") == "tok-A"
    assert _read_capability("never-set/repo") == ""


def test_read_capability_distinguishes_punctuation_variants(monkeypatch):
    """Round-2 P1.2 regression guard. Under the round-1 suffix encoding
    `octo/my.repo`, `octo/my_repo`, and `octo/my-repo` collapsed to
    `WORKFLOW_GITHUB_PR_CAPABILITY_REPO_OCTO_MY_REPO` and shared one
    token. The JSON-map keys are the raw destination strings, so each
    variant maps to its own token."""
    monkeypatch.setenv(
        _CAPABILITIES_ENV,
        json.dumps({
            "octo/my.repo": "tok-dot",
            "octo/my_repo": "tok-under",
            "octo/my-repo": "tok-dash",
        }),
    )
    assert _read_capability("octo/my.repo") == "tok-dot"
    assert _read_capability("octo/my_repo") == "tok-under"
    assert _read_capability("octo/my-repo") == "tok-dash"
    # Lookups for destinations not in the map return empty.
    assert _read_capability("octo/MY.REPO") == ""


def test_read_capability_empty_destination_returns_empty():
    assert _read_capability("") == ""


def test_read_capability_unset_env_returns_empty():
    """No env set -> empty token -> missing_capability dry-run."""
    # _clean_capability_env autouse already cleared the env.
    assert _read_capability("Jonnyton/Workflow") == ""


def test_read_capability_malformed_json_logs_and_returns_empty(monkeypatch):
    """Malformed JSON is logged loudly (the operator sees the warning)
    but never raises — the lookup collapses to missing_capability."""
    monkeypatch.setenv(_CAPABILITIES_ENV, "{not valid json}")
    assert _read_capability("Jonnyton/Workflow") == ""


def test_read_capability_non_object_json_returns_empty(monkeypatch):
    """The env value must decode to a JSON object. A list, scalar, or
    null all collapse to no-capability rather than crashing."""
    for value in ("[\"Jonnyton/Workflow\"]", "\"tok\"", "null", "42"):
        monkeypatch.setenv(_CAPABILITIES_ENV, value)
        assert _read_capability("Jonnyton/Workflow") == ""


def test_read_capability_strips_empty_token_entries(monkeypatch):
    """Whitespace-only or empty-string values are treated as "not
    configured" so a half-filled map doesn't accidentally grant
    capability for a placeholder entry."""
    monkeypatch.setenv(
        _CAPABILITIES_ENV,
        json.dumps({
            "Jonnyton/Workflow": "",
            "octo/other": "   ",
            "octo/real": "tok-real",
        }),
    )
    assert _read_capability("Jonnyton/Workflow") == ""
    assert _read_capability("octo/other") == ""
    assert _read_capability("octo/real") == "tok-real"


# ---------------------------------------------------------------------------
# Gate 1 — capability env missing
# ---------------------------------------------------------------------------


def test_destination_present_capability_missing_returns_dry_run(universe_dir):
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_2"
    assert result["reason"] == "missing_capability"
    assert result["destination"] == _DESTINATION
    # Round-2 fix — evidence names the JSON-map env var and the literal
    # destination key the host needs to add, never a collision-prone
    # uppercased suffix.
    assert result["capability_env_var"] == _CAPABILITIES_ENV
    assert result["capability_lookup_failed_for"] == _DESTINATION
    assert _CAPABILITIES_ENV in result["hint"]
    assert _DESTINATION in result["hint"]


def test_capability_token_never_echoed_into_evidence(universe_dir, monkeypatch):
    """The token MUST NOT appear in any returned evidence shape — that's
    the core invariant separating Phase 2 from the Phase-1 self-mintable
    ack."""
    _set_capability(monkeypatch, _DESTINATION, "super-secret-pat-DO-NOT-LEAK")
    # No consent grant -> closes at gate 2; evidence should not include
    # the capability token.
    packet = _make_packet()
    result = run_github_pr_effector(
        node_id="emit",
        output_keys=["pr_packet"],
        run_state={"pr_packet": packet},
        base_path=universe_dir,
        run_id="run-1",
    )
    blob = json.dumps(result)
    assert "super-secret-pat-DO-NOT-LEAK" not in blob, (
        "capability token must NEVER appear in branch-visible evidence"
    )


# ---------------------------------------------------------------------------
# Gate 2 — consent missing
# ---------------------------------------------------------------------------


def test_capability_present_consent_missing_returns_dry_run(
    universe_dir, monkeypatch,
):
    _set_capability(monkeypatch, _DESTINATION, "tok")
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_2"
    assert result["reason"] == "missing_consent"
    assert result["destination"] == _DESTINATION
    # The hint should mention the grant action so the chatbot knows
    # what to surface to the user.
    assert "grant_effector_consent" in result["hint"]


def test_consent_destination_must_match_exactly(universe_dir, monkeypatch):
    """A grant for repo A must NOT authorize writes to repo B."""
    _set_capability(monkeypatch, _DESTINATION, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination="some-other/repo",  # different destination
        granted_by="host",
    )
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["reason"] == "missing_consent"


# ---------------------------------------------------------------------------
# Gate 3 — idempotency dedup (terminal-succeeded row dedup-hits)
# ---------------------------------------------------------------------------


def test_idempotency_hit_returns_recorded_evidence_no_subprocess(
    universe_dir, monkeypatch,
):
    _set_capability(monkeypatch, _DESTINATION, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )
    # Pre-seed a terminal-succeeded receipt (legacy round-1 shape).
    record_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        evidence={
            "pr_url": "https://github.com/Jonnyton/Workflow/pull/901",
            "pr_number": 901,
        },
        run_id="prior-run",
        created_at=1700.0,
    )
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-retry",
        )
    mock_run.assert_not_called()
    assert result["idempotency_dedup_hit"] is True
    assert result["phase"] == "phase_2"
    assert result["evidence"]["pr_number"] == 901
    assert result["recorded_run_id"] == "prior-run"
    assert result["recorded_at"] == 1700.0


def test_idempotency_miss_when_hint_omitted(universe_dir, monkeypatch):
    """A packet without ``idempotency_hint`` is treated as 'always miss'
    so the caller can opt out of dedup. The real-write path then fires."""
    _set_capability(monkeypatch, _DESTINATION, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )
    packet = _make_packet(idempotency_hint=None)
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/777\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_called_once()
    assert result["pr_number"] == 777
    # No receipt should have been recorded (no hint).
    assert lookup_receipt(
        universe_dir,
        idempotency_hint="",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    ) is None


# ---------------------------------------------------------------------------
# Happy path — all three gates open -> real invocation + terminal receipt
# ---------------------------------------------------------------------------


def _open_all_gates(universe_dir, monkeypatch):
    _set_capability(monkeypatch, _DESTINATION, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )


def test_all_gates_open_invokes_gh_and_records_receipt(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout=(
            "Creating draft pull request for "
            "auto/loop-2/cycle-001 into main\n"
            "https://github.com/Jonnyton/Workflow/pull/1234\n"
        ),
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_called_once()
    cmd = mock_run.call_args[0][0]
    # Verify the invocation shape — repo + title + base + head + draft + label.
    assert cmd[0] == "gh"
    assert "--repo" in cmd
    assert cmd[cmd.index("--repo") + 1] == _DESTINATION
    assert "--title" in cmd
    assert "--base" in cmd
    assert "--head" in cmd
    assert cmd[cmd.index("--head") + 1] == _HEAD_BRANCH
    assert "--draft" in cmd
    assert "writer:loop-2" in cmd  # label passthrough

    assert result["phase"] == "phase_2"
    assert result["pr_url"] == "https://github.com/Jonnyton/Workflow/pull/1234"
    assert result["pr_number"] == 1234
    assert result["destination"] == _DESTINATION
    assert result["matched_output_key"] == "pr_packet"
    # Capability token must NOT be in the result.
    assert "tok" not in json.dumps(result)

    # Receipt is in the terminal `succeeded` state with the PR evidence.
    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["run_id"] == "run-1"
    assert receipt["evidence"]["pr_number"] == 1234
    assert receipt["status"] == STATUS_SUCCEEDED


def test_second_run_with_same_hint_is_dedup_hit(universe_dir, monkeypatch):
    """Two back-to-back runs with the same idempotency_hint must invoke
    gh exactly once. The second run returns the recorded receipt."""
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/42\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        first = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
        second = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-2-retry",
        )
    assert mock_run.call_count == 1
    assert first["pr_number"] == 42
    assert second["idempotency_dedup_hit"] is True
    assert second["evidence"]["pr_number"] == 42
    assert second["recorded_run_id"] == "run-1"


# ---------------------------------------------------------------------------
# Failure paths — reservation released to status=failed; no terminal receipt
# ---------------------------------------------------------------------------


def test_gh_nonzero_exit_releases_reservation_to_failed(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=2,
        stdout="",
        stderr="gh: GraphQL: Branch already has an open pull request\n",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-fail",
        )
    assert result["error_kind"] == "gh_nonzero_exit"
    assert "exit 2" in result["error"]
    assert result.get("reservation_released") is True
    # The reservation row exists but is now status=failed, so a retry
    # under the same hint can re-reserve.
    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["status"] == STATUS_FAILED


def test_gh_not_installed_and_api_unavailable_returns_structured_error(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    with (
        patch(
            "workflow.effectors.github_pr.subprocess.run",
            side_effect=FileNotFoundError("gh"),
        ),
        patch(
            "workflow.effectors.github_pr.urllib.request.urlopen",
            side_effect=urllib.error.URLError("offline"),
        ),
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    assert result["error_kind"] == "github_api_error"
    assert "GitHub API request failed" in result["error"]


def test_gh_not_installed_falls_back_to_github_api(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()

    class FakeResponse:
        headers = {}

        def __init__(self, payload: dict):
            self._payload = payload

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self):
            return json.dumps(self._payload).encode("utf-8")

    requests = []

    def fake_urlopen(req, timeout):
        requests.append((req, timeout, req.data))
        if req.full_url.endswith("/pulls"):
            body = json.loads(req.data.decode("utf-8"))
            assert body["title"] == packet["payload"]["title"]
            assert body["base"] == "main"
            assert body["head"] == _HEAD_BRANCH
            assert body["draft"] is True
            assert req.headers["Authorization"] == "Bearer tok"
            return FakeResponse({
                "html_url": "https://github.com/Jonnyton/Workflow/pull/5678",
                "number": 5678,
            })
        if req.full_url.endswith("/issues/5678/labels"):
            body = json.loads(req.data.decode("utf-8"))
            assert body == {"labels": ["writer:loop-2"]}
            return FakeResponse({"labels": []})
        raise AssertionError(f"unexpected URL {req.full_url}")

    with (
        patch(
            "workflow.effectors.github_pr.subprocess.run",
            side_effect=FileNotFoundError("gh"),
        ) as mock_run,
        patch("workflow.effectors.github_pr.urllib.request.urlopen", fake_urlopen),
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )

    mock_run.assert_called_once()
    assert len(requests) == 2
    assert result["phase"] == "phase_2"
    assert result["pr_url"] == "https://github.com/Jonnyton/Workflow/pull/5678"
    assert result["pr_number"] == 5678
    assert result["invocation_mode"] == "github_api"
    assert "tok" not in json.dumps(result)

    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["status"] == STATUS_SUCCEEDED
    assert receipt["evidence"]["pr_number"] == 5678


def test_gh_timeout_returns_structured_error(universe_dir, monkeypatch):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        side_effect=subprocess.TimeoutExpired(cmd="gh", timeout=60),
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    assert result["error_kind"] == "gh_invocation_failed"


def test_gh_returns_zero_but_no_pr_url_returns_error(
    universe_dir, monkeypatch,
):
    """If gh exits 0 but stdout is empty or unparseable, we treat it as a
    nonzero-exit-like failure rather than silently recording a phantom
    receipt with an empty url. Hard rule #8 — fail loudly."""
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout="ok\n",  # no URL
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    assert result["error_kind"] == "gh_nonzero_exit"
    # The reservation is released to failed so a retry can re-reserve.
    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["status"] == STATUS_FAILED


# ---------------------------------------------------------------------------
# Branch-level dispatch threads base_path + run_id
# ---------------------------------------------------------------------------


def test_run_effects_for_branch_passes_base_path_and_run_id(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="emit",
                display_name="Emit",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/9\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ):
        ev_map = run_effects_for_branch(
            branch=branch,
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="dispatch-run",
        )
    ev = ev_map["emit"][EXTERNAL_WRITE_SINK_GITHUB_PR]
    assert ev["pr_number"] == 9
    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["run_id"] == "dispatch-run"
    assert receipt["status"] == STATUS_SUCCEEDED


# ---------------------------------------------------------------------------
# Backward compatibility — Phase 1 packets (no destination)
# ---------------------------------------------------------------------------


def test_packet_without_destination_returns_phase_1_evidence(
    universe_dir, monkeypatch,
):
    """A packet that omits the new ``destination`` field is by definition
    a Phase-1 packet. The effector returns the Phase-1 dry-run shape so
    existing consumers don't observe a behavior change."""
    # All gates open at Phase 2, but the packet lacks the destination field.
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet(destination=None)
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_1"
    assert result["mode"] == "dry_run_default"
    assert result["enabled_explicit"] is False
    assert result["intent"]["sink"] == EXTERNAL_WRITE_SINK_GITHUB_PR


def test_phase_2_dry_run_does_not_carry_phase_1_mode_keys(
    universe_dir, monkeypatch,
):
    """Phase-2 dry-runs (missing capability/consent) must NOT smuggle in
    the Phase-1 ``mode`` / ``enabled_explicit`` keys. Those keys are
    Phase-1-only signals and would confuse consumers that branch on
    them."""
    packet = _make_packet()
    result = run_github_pr_effector(
        node_id="emit",
        output_keys=["pr_packet"],
        run_state={"pr_packet": packet},
        base_path=universe_dir,
        run_id="run-1",
    )
    assert result["phase"] == "phase_2"
    assert "mode" not in result
    assert "enabled_explicit" not in result


def test_phase_2_packet_with_capability_but_no_base_path_is_dry_run(
    monkeypatch,
):
    """If the effector is invoked without a base_path (e.g. by a legacy
    caller), Phase-2-shaped packets still cannot mint a real write.
    Capability env can be read, but consent lookup has nowhere to look,
    so we must fall back to ``missing_consent`` dry-run."""
    _set_capability(monkeypatch, _DESTINATION, "tok")
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=None,
            run_id="",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["reason"] == "missing_consent"


# ---------------------------------------------------------------------------
# Pending-state sanity: a reserved-but-not-finalized row blocks duplicates
# ---------------------------------------------------------------------------


def test_existing_pending_reservation_blocks_concurrent_in_flight(
    universe_dir, monkeypatch,
):
    """A non-stale pending reservation held by ANOTHER run is reported
    as concurrent_in_flight — the current call must dry-run rather than
    fire a duplicate. (Atomicity tests in
    test_external_write_phase_2_atomicity.py exercise the race more
    thoroughly; this is the in-isolation smoke check.)"""
    _open_all_gates(universe_dir, monkeypatch)
    # Manually drop a pending row into the store, simulating another
    # worker holding the reservation.
    import time as _time

    from workflow.storage.external_write_receipts import (
        _connect,
        initialize_receipts_db,
    )
    initialize_receipts_db(universe_dir)
    with _connect(universe_dir) as conn:
        conn.execute(
            "INSERT INTO external_write_receipts ("
            "  idempotency_hint, sink, evidence_json, run_id, "
            "  created_at, status"
            ") VALUES (?, ?, '{}', ?, ?, ?)",
            (
                "loop-2-cycle-001", EXTERNAL_WRITE_SINK_GITHUB_PR,
                "other-worker-run", _time.time(), STATUS_PENDING,
            ),
        )
        conn.commit()

    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="my-run",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["reason"] == "concurrent_in_flight"
    assert result["held_by_run_id"] == "other-worker-run"


# ---------------------------------------------------------------------------
# Operator kill switch (round-3 P1 fix for Codex round-2 on PR #969)
# ---------------------------------------------------------------------------


def test_kill_switch_bypasses_all_gates_when_truthy(
    universe_dir, monkeypatch,
):
    """``WORKFLOW_EXTERNAL_WRITE_DRY_RUN=1`` is the operator
    panic-button override. Round-1 of Phase 2 inadvertently left this
    env recognized-but-ignored; Codex round-2 caught the
    documentation/behavior drift and asked for the override to be
    restored as a documented kill switch.

    Contract: even with ALL three gates wide open (capability set,
    consent granted, idempotency clean), a truthy DRY_RUN env must
    short-circuit to dry-run evidence and never invoke ``gh``.
    """
    _open_all_gates(universe_dir, monkeypatch)
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", "1")
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-killed",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_2"
    assert result["reason"] == "operator_kill_switch_active"
    assert result["kill_switch_env"] == "WORKFLOW_EXTERNAL_WRITE_DRY_RUN"
    assert result["matched_output_key"] == "pr_packet"
    hint_lc = result["hint"].lower()
    assert (
        "panic-button" in result["hint"]
        or "kill switch" in hint_lc
        or "override" in hint_lc
    )
    # Make absolutely sure no reservation was written either — the kill
    # switch fires before the reservation path, so the store stays clean.
    assert lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    ) is None


@pytest.mark.parametrize("value", ["1", "true", "True", "yes", "ON"])
def test_kill_switch_truthy_variants(universe_dir, monkeypatch, value):
    """All truthy spellings (matching the existing ``_TRUTHY`` set) must
    activate the override."""
    _open_all_gates(universe_dir, monkeypatch)
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", value)
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-killed",
        )
    mock_run.assert_not_called()
    assert result["reason"] == "operator_kill_switch_active"


@pytest.mark.parametrize("value", ["", "0", "false", "no", "off"])
def test_kill_switch_falsy_variants_do_not_override(
    universe_dir, monkeypatch, value,
):
    """Falsy / empty values leave the gates governing the outcome —
    a truthy capability+consent+no-receipt combo must produce a real
    invocation (the mocked gh subprocess fires once)."""
    _open_all_gates(universe_dir, monkeypatch)
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", value)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/4242\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-real",
        )
    mock_run.assert_called_once()
    assert result["pr_number"] == 4242
    assert result.get("reason") != "operator_kill_switch_active"


def test_kill_switch_unset_does_not_override(universe_dir, monkeypatch):
    """Unset env (autouse fixture clears it) leaves gates governing —
    the normal real-write path fires."""
    _open_all_gates(universe_dir, monkeypatch)
    # autouse _clean_capability_env already cleared DRY_RUN; confirm.
    import os as _os
    assert "WORKFLOW_EXTERNAL_WRITE_DRY_RUN" not in _os.environ
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/4242\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-real",
        )
    mock_run.assert_called_once()
    assert result["pr_number"] == 4242


def test_kill_switch_bypasses_phase_1_path_too(universe_dir, monkeypatch):
    """Phase-1-shaped packets (no ``destination``) must also honor the
    kill switch — the override fires at the top of the effector,
    BEFORE the Phase-1 / Phase-2 branch."""
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", "1")
    packet = _make_packet(destination=None)
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-killed",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["reason"] == "operator_kill_switch_active"


def test_kill_switch_evidence_never_leaks_capability_token(
    universe_dir, monkeypatch,
):
    """When the kill switch fires alongside a configured capability map,
    the dry-run evidence must NOT contain the token — same invariant
    as the rest of Phase 2."""
    _set_capability(monkeypatch, _DESTINATION, "super-secret-pat-no-leak")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )
    monkeypatch.setenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", "1")
    packet = _make_packet()
    result = run_github_pr_effector(
        node_id="emit",
        output_keys=["pr_packet"],
        run_state={"pr_packet": packet},
        base_path=universe_dir,
        run_id="run-1",
    )
    assert result["reason"] == "operator_kill_switch_active"
    assert "super-secret-pat-no-leak" not in json.dumps(result)
